### PR TITLE
Move overkiz.event to the end of the `coordinator` logic

### PR DESCRIPTION
**Pull request by iMicknl**
@tetienne wouldn't it make sense to have this code at the end of our coordinator logic? This means that it won't interfere with our core functions at least.

<a href="https://gitpod.io/#https://github.com/iMicknl/ha-tahoma/pull/638"></a>

### CODE REVIEW

**Comment by tetienne** [comment]
What do you mean by interfere?

**Comment by iMicknl** [comment]
> What do you mean by interfere?

To make sure that issues like this https://github.com/iMicknl/ha-tahoma/issues/629, won't disable core functionality (like state etc.).

**Comment by tetienne** [comment]
It should not happen anymore with my fix. But OK.

**Review by tetienne — APPROVED** [review]

**Comment by iMicknl** [comment]
> It should not happen anymore with my fix. But OK.

I agree! However, it just made me think that we should try to have our most important logic before other logic.

**Pull request merged**
