### PR TITLE
Add Boost Mode Duration and Away Mode Duration

### PR DESCRIPTION
**Pull request by iMicknl**

### CODE REVIEW

**Comment by vlebourl** [comment]
Which DHWP device does this relate to? According to #617 commands differ depending on the device... I haven't found an elegant way to combine both listed in that PR yet...

**Comment by iMicknl** [comment]
@vlebourl this is related to https://github.com/iMicknl/ha-tahoma/issues/664.

Perhaps it makes more sense to support BoostModeDuration only via a number entity, and not via the water heater? Since you have to set it for a number of days.

**Comment by vlebourl** [comment]
Should we have a switch as well? app looks like this for boost mode for `io:AtlanticDomesticHotWaterProductionV2_CE_FLAT_C2_IOComponent`
image

**Comment by foXaCe** [comment]
@iMicknl hello, is it possible to merge this function in master?
please

**Comment by iMicknl** [comment]
> @iMicknl hello, is it possible to merge this function in master? please

We can look to add this feature to core, however this feature has not been tested very well. Which device do you have and do you use the away mode duration, or the boost mode duration?

**Comment by foXaCe** [comment]
I miss the Boost function.
I can pass you my cozytouch password if you need to test.

**Comment by iMicknl** [comment]
@foXaCe please contact me on Discord and we can have a look the coming weeks. I will see if we can add this feature to core.

**Comment by iMicknl** [comment]
superseeded by https://github.com/home-assistant/core/pull/76690

**Pull request closed without merging**
