### PR TITLE
Add basic alarm component

### PR DESCRIPTION
**Pull request by iMicknl**

### CODE REVIEW

**Comment by Glenn1986** [comment]
Hi guys, i'm using your component somfy tahoma. Beautifull work! I'm wondering when the alarm will be integrated? I'm a volunteer for testing if needed ;) Thanks

**Comment by iMicknl** [comment]
@Glenn1986 which device do you have? Could you create a new issue with all the details of your device. You are the only tester for now. :)

**Comment by WhistleMaster** [comment]
Would the Somfy Protect alarm be supported with this integration ? Seems that the Somfy One / One+, Somfy Home Alarm and Somfy Security Camera can be integrated with TaHoma [support.somfyprotect.com](https://support.somfyprotect.com/hc/en-us/articles/115003963229-How-to-use-your-Somfy-Protect-products-with-TaHoma). 

Thanks !

**Comment by vlebourl** [comment]
Hi @WhistleMaster , thanks for your interest. 
The alarm component is still under development, but we want to support as many devices as possible. Do you own some of them? If so, can you test [this branch](https://github.com/iMicknl/ha-tahoma/tree/add_basic_alarm_component)? To do so, download the zip following [this link](https://github.com/iMicknl/ha-tahoma/archive/add_basic_alarm_component.zip), unzip it, and replace the `tahoma` directory installed by HACS by the one in the zip. Once done, restart HA and give it a try. 
As we don't own alarms on our end, we rely on the community to help us develop it.

**Comment by WhistleMaster** [comment]
I have the Somfy Home Alarm and the Somfy Security Camera, but not yet the TaHoma box. I'll get one to do the tests.

**Comment by iMicknl** [comment]
@vlebourl I think this branch is broken currently, hopefully I have some spare time this / next week to fix it. :)

I believe the Security Camera is hard to integrate with HomeAssistant by the way..

**Comment by iMicknl** [comment]
@WhistleMaster would you be willing to help me a bit with the Somfy Home Alarm and Security Camera's? I don't have any devices to test.

**Comment by Glenn1986** [comment]
Hi mick I would like to help you! The problem at the moment is that I can not login on tahomalink.com. Very strange though, I can login on somfy.be and than open my tahomo box. I did mail to somfy but no answer at the moment. I let you know when the problem is solved.

**Comment by WhistleMaster** [comment]
Sure ! That’s funny because I received the Tahoma box yesterday. I just need to setup everything and then I can help you on that !

**Comment by iMicknl** [comment]
@WhistleMaster haha, that's a great timing. Based on my research, it will be really hard to support the cameras. They are not controlled via Tahomalink API, it looks like there is a different platform for Somfy Protect...

Home Alarm could probably be supported.

**Comment by WhistleMaster** [comment]
But according to this [link](https://support.somfyprotect.com/hc/en-us/articles/115003963229-How-to-use-your-Somfy-Protect-products-with-TaHoma), it seems that the camera feed can be seen from the Tahoma App, right ?

**Comment by iMicknl** [comment]
> But according to this [link](https://support.somfyprotect.com/hc/en-us/articles/115003963229-How-to-use-your-Somfy-Protect-products-with-TaHoma), it seems that the camera feed can be seen from the Tahoma App, right ?

True, but I can not seem to find it in their API. Let's have a closer look over the coming weeks, after you have installed your box / devices 👍

**Pull request closed without merging**
