### PR TITLE
Migrate to native unit of measurement

### LINKED ISSUE #547: HA warning: unit_of_measurement
### Did you read the instructions?

- [X] I have read the [README](https://github.com/iMicknl/ha-tahoma/blob/master/README.md), including the [advanced debugging](https://github.com/iMicknl/ha-tahoma/blob/master/README.md#advanced) section.

### The problem

After updating HA, I get some warnings

### What version of this integration (ha-tahoma) has the issue?

master

### What version of Home Assistant Core has the issue?

2021,9,0

### Which gateway / hub do you use?

TaHoma

### Device model

-

### Device type

-

### Additional information

Super nice bug report form! Well done

### Relevant log output

```shell
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:58 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:59 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:59 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:59 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:59 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:59 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:59 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:59 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:59 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:59 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:59 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
2021-09-01 22:10:59 WARNING (MainThread) [homeassistant.components.sensor] custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.
```
```

### PR DESCRIPTION
**Pull request by tetienne**
Fix #547

See https://developers.home-assistant.io/docs/core/entity/sensor

### CODE REVIEW

**Review by iMicknl — COMMENTED** [review]
Looks good! However, should you not make changes here as well:

https://github.com/iMicknl/ha-tahoma/blob/d46a4af3815f864a1238e6ba5d1da6d5f9a26841/custom_components/tahoma/sensor.py#L338-L349

**Comment by tetienne** [comment]
Good question. I will check.

**Comment by tetienne** [comment]
@iMicknl Ready to be merged.

**Review by iMicknl — APPROVED** [review]

**Comment by dhover** [comment]
I've upgraded to 2.7.1 but I still get the error:

`Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:151
Integration: Sensor (documentation, issues)
First occurred: 1:36:56 PM (1 occurrences)
Last logged: 1:36:56 PM

custom_components.tahoma.sensor is setting 'unit_of_measurement' on an instance of SensorEntityDescription, this is not valid and will be unsupported from Home Assistant 2021.11. Please report it to the custom component author.`

**Pull request merged**
