### PR TITLE
Add more ui_classes and sort them alphabetically

### PR DESCRIPTION
**Pull request by iMicknl**
Merge into master after #160 is merged.

### CODE REVIEW

**Comment by vlebourl** [comment]
isn't that a duplicate of #150?

**Comment by iMicknl** [comment]
@vlebourl yes partly. However for now I just added the already supported platforms and I reordered the lists in the new structure.

**Comment by vlebourl** [comment]
Nice. Do we really need to keep the other branch?

**Comment by iMicknl** [comment]
@vlebourl I didn't want to close it for now, since you are also adding more classes as None. I am still not sure what I prefer / what would be nice. Let's have a look after the new integration is merged and discuss.

**Pull request merged**
