### PR TITLE
add black check to ci cd

### PR DESCRIPTION
**Pull request by vlebourl**

### CODE REVIEW

**Comment by vlebourl** [comment]
black can quickly be applied to all files with something like:
`find . -name "*.py" -execdir black {}  \;`

**Comment by iMicknl** [comment]
Looks good! Not sure if they are still using flake8 in core though, but I can't hurt to have it here I guess?

>As part of adopting Black, all style checks in flake8 and pylint have been disabled.
https://developers.home-assistant.io/blog/2019/07/31/black/

**Comment by vlebourl** [comment]
I think they do, and I took part of there setup.cfg file that configure the checks to be as close as possible to their standards

**Comment by iMicknl** [comment]
@vlebourl cool! Just merge this one when you are ready.

**Pull request merged**
